export const types = {
    MAKE_REQUEST_GENERAL: 'MAKE_REQUEST_GENERAL',
    GET_DATA_BEER_PRODUCTS: 'GET_DATA_BEER_PRODUCTS',
    GET_DATA_PRESENCE_SHARE: 'GET_DATA_PRESENCE_SHARE',
    GET_DATA_PRICE_EVOLUTION: 'GET_DATA_PRICE_EVOLUTION'
};